/**
 * ArchitectOS SAST Rule Registry
 * Central registry for all SAST rules. Rules are loaded by sastScanner.js.
 * Each rule has: id, name, severity, cwe, pattern, isLiteralSafe, category
 */

const RULE_CATEGORIES = {
  INJECTION: 'Injection',
  XSS: 'Cross-Site Scripting',
  AUTH: 'Authentication & Authorization',
  CRYPTO: 'Cryptography',
  SECRETS: 'Secrets & Credentials',
  INFRA: 'Infrastructure & Configuration',
  DATA: 'Sensitive Data Exposure',
  RESOURCE: 'Resource Management',
};

const SAST_RULES = [
  // ─── EXISTING RULES (kept for backwards compatibility) ───────────────────

  {
    id: 'SAST-SQLI-001',
    name: 'SQL Injection via Dynamic String Concatenation',
    severity: 'CRITICAL',
    cwe: 'CWE-89',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER)\s+.*?(?:["']\s*\+\s*[A-Za-z_$]|[A-Za-z_$0-9)]\s*\+\s*["']|\bformat\s*\(|f["'].*?\{|\$\{).*?(?:FROM|WHERE|SET|VALUES)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-XSS-001',
    name: 'Cross-Site Scripting (XSS) via Dangerous DOM Injection',
    severity: 'HIGH',
    cwe: 'CWE-79',
    category: RULE_CATEGORIES.XSS,
    pattern: /(dangerouslySetInnerHTML|innerHTML\s*=|document\.write\s*\(|v-html\s*=)/i,
    isLiteralSafe: true,
  },
  {
    id: 'SAST-RCE-001',
    name: 'Command / Process Execution Vulnerability',
    severity: 'CRITICAL',
    cwe: 'CWE-78',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:child_process\.exec\s*\(|os\.system\s*\(|subprocess\.(?:Popen|call|run)\s*\(.*?shell\s*=\s*True)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-EVAL-001',
    name: 'Unsafe Dynamic Code Execution (eval / exec)',
    severity: 'HIGH',
    cwe: 'CWE-95',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:\beval\s*\(|\bpython_exec\s*\(|new\s+Function\s*\()/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-SSRF-001',
    name: 'Potential Server-Side Request Forgery (SSRF)',
    severity: 'HIGH',
    cwe: 'CWE-918',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:fetch\s*\(req\.(?:query|params|body)|requests\.(?:get|post)\s*\([^)]*?(?:req|user_input|url_param))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PATH-001',
    name: 'Unsafe Path Traversal in File Operations',
    severity: 'HIGH',
    cwe: 'CWE-22',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:fs\.(?:readFile|readFileSync|createReadStream)\s*\([^)]*?(?:req\.|params\.|query\.)|open\s*\([^)]*?(?:user_input|request\.|path_param))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-CRYPTO-001',
    name: 'Use of Weak Cryptographic Hash Algorithm (MD5/SHA1)',
    severity: 'MEDIUM',
    cwe: 'CWE-327',
    category: RULE_CATEGORIES.CRYPTO,
    pattern: /(?:crypto\.createHash\s*\(\s*['"](?:md5|sha1)['"]\s*\)|hashlib\.(?:md5|sha1)\s*\()/i,
    isLiteralSafe: true,
  },
  {
    id: 'SAST-CORS-001',
    name: "Overly Permissive CORS Policy (Access-Control-Allow-Origin: *)",
    severity: 'MEDIUM',
    cwe: 'CWE-942',
    category: RULE_CATEGORIES.INFRA,
    pattern: /(?:Access-Control-Allow-Origin\s*['"]?\s*:\s*['"][*]['"]|allow_origins\s*=\s*\[\s*['"][*]['"]\s*\])/i,
    isLiteralSafe: true,
  },
  {
    id: 'SAST-JWT-001',
    name: 'Hardcoded JWT Signing Key or Secret Constant',
    severity: 'HIGH',
    cwe: 'CWE-798',
    category: RULE_CATEGORIES.SECRETS,
    pattern: /(?:jwt\.sign\s*\([^)]*?['"][a-zA-Z0-9_\-]{8,}['"]|jwt\.verify\s*\([^)]*?['"][a-zA-Z0-9_\-]{8,}['"]|SECRET_KEY\s*=\s*['"][a-zA-Z0-9_\-]{6,}['"])/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-SECRET-001',
    name: 'Hardcoded High-Entropy API Key / Token',
    severity: 'CRITICAL',
    cwe: 'CWE-798',
    category: RULE_CATEGORIES.SECRETS,
    pattern: /(?:AKIA[0-9A-Z]{16}|ghp_[a-zA-Z0-9]{36}|eyJhbGciOi[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+|-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----\s*MII)/,
    isLiteralSafe: false,
  },

  // ─── NEW RULES (v1.2.0+) ─────────────────────────────────────────────────

  {
    id: 'SAST-PP-001',
    name: 'Prototype Pollution via __proto__ or constructor.prototype Assignment',
    severity: 'HIGH',
    cwe: 'CWE-1321',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:__proto__\s*\[|__proto__\s*=|constructor\s*\.\s*prototype\s*\[|Object\.assign\s*\([^,]+,\s*(?:req\.|params\.|body\.))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-OR-001',
    name: 'Open Redirect via Unvalidated User-Controlled URL',
    severity: 'HIGH',
    cwe: 'CWE-601',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /res\.redirect\s*\(\s*(?:req\.(?:query|params|body)|params\.|query\.)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-DOS-001',
    name: 'ReDoS — Catastrophic Backtracking in Regex',
    severity: 'MEDIUM',
    cwe: 'CWE-1333',
    category: RULE_CATEGORIES.RESOURCE,
    pattern: /new\s+RegExp\s*\(\s*(?:req\.|params\.|query\.|body\.|user)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-DESER-001',
    name: 'Unsafe Deserialization of User-Controlled Data',
    severity: 'CRITICAL',
    cwe: 'CWE-502',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:JSON\.parse\s*\([^)]*?(?:req\.|params\.|body\.|query\.)|unserialize\s*\(|yaml\.load\s*\([^,)]*?(?:req\.|user))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-LOG-001',
    name: 'Sensitive Data Exposed in Logs',
    severity: 'MEDIUM',
    cwe: 'CWE-532',
    category: RULE_CATEGORIES.DATA,
    pattern: /console\.(?:log|info|warn|error)\s*\([^)]*?(?:password|passwd|secret|token|api_key|apikey|credential|ssn|credit_card)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-NOSQLI-001',
    name: 'NoSQL Injection via User-Controlled Query Operator',
    severity: 'CRITICAL',
    cwe: 'CWE-943',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:\.find\s*\(\s*\{[^}]*?\$where|\.find\s*\(\s*(?:req\.|params\.|body\.|query\.)|collection\.(?:find|findOne|update)\s*\(\s*(?:req\.|params\.))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-TIMING-001',
    name: 'Timing Attack via Non-Constant-Time String Comparison',
    severity: 'MEDIUM',
    cwe: 'CWE-208',
    category: RULE_CATEGORIES.CRYPTO,
    pattern: /(?:token|secret|password|hash|hmac|signature|api_key)\s*(?:===|!==|==|!=)\s*(?:req\.|params\.|body\.|query\.|user\.)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-CMD-001',
    name: 'Shell Command Injection via Template Literal or Concatenation',
    severity: 'CRITICAL',
    cwe: 'CWE-78',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:exec|execSync|spawn|spawnSync)\s*\(\s*`[^`]*\$\{|(?:exec|execSync)\s*\(\s*[^,)]*?\+\s*(?:req\.|params\.|body\.|query\.)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-UPLOAD-001',
    name: 'Unrestricted File Upload Without MIME/Extension Validation',
    severity: 'HIGH',
    cwe: 'CWE-434',
    category: RULE_CATEGORIES.INFRA,
    pattern: /(?:req\.files?|multer|formidable|busboy)[^;]*(?:\.path|\.filename|\.originalname)[^;]*(?:fs\.|path\.join|writeFile)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-WEAK-RAND-001',
    name: 'Weak Randomness for Security-Sensitive Token Generation',
    severity: 'HIGH',
    cwe: 'CWE-338',
    category: RULE_CATEGORIES.CRYPTO,
    pattern: /Math\.random\s*\(\s*\)[^;]*(?:token|secret|session|csrf|key|nonce|salt|id)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-OPEN-REDIR-001',
    name: 'Client-Side Open Redirect via Unvalidated window.location Assignment',
    severity: 'HIGH',
    cwe: 'CWE-601',
    category: RULE_CATEGORIES.XSS,
    pattern: /window\.location(?:\.href)?\s*=\s*(?:.*?(?:params\.|query\.|searchParams\.get|location\.search|location\.hash))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-STORE-001',
    name: 'Sensitive Data Stored in localStorage or sessionStorage',
    severity: 'MEDIUM',
    cwe: 'CWE-922',
    category: RULE_CATEGORIES.DATA,
    pattern: /(?:localStorage|sessionStorage)\.setItem\s*\([^)]*?(?:token|password|secret|api_key|session|credential)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-ENV-001',
    name: 'Hardcoded Fallback Value for Security-Sensitive Environment Variable',
    severity: 'MEDIUM',
    cwe: 'CWE-547',
    category: RULE_CATEGORIES.SECRETS,
    pattern: /process\.env\.(?:SECRET|PASSWORD|API_KEY|TOKEN|PRIVATE_KEY|DATABASE_URL|DB_PASS)\s*\|\|\s*['"][^'"]{3,}['"]/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-CLICKJACK-001',
    name: 'Missing Clickjacking Protection (X-Frame-Options / CSP)',
    severity: 'LOW',
    cwe: 'CWE-1021',
    category: RULE_CATEGORIES.INFRA,
    pattern: /helmet\s*\(\s*\{\s*[^}]*frameguard\s*:\s*false/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-LDAP-001',
    name: 'LDAP Injection via Unsanitized User Input',
    severity: 'HIGH',
    cwe: 'CWE-90',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:ldap(?:js)?\.search|client\.search)\s*\([^)]*?(?:\+\s*(?:req\.|params\.|query\.|body\.)|`[^`]*\$\{(?:req\.|params\.))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-XXE-001',
    name: 'XML External Entity (XXE) via User-Controlled XML Parsing',
    severity: 'HIGH',
    cwe: 'CWE-611',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:xml2js|fast-xml-parser|DOMParser|parseString|parseXml)\s*[.(][^;]*(?:req\.|body\.|params\.|query\.)/i,
    isLiteralSafe: false,
  },

  // ─── PYTHON SPECIFIC SAST RULES ─────────────────────────────────────────

  {
    id: 'SAST-PY-PICKLE-001',
    name: 'Python Unsafe Pickle Deserialization Vulnerability',
    severity: 'CRITICAL',
    cwe: 'CWE-502',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /pickle\.(?:loads|load)\s*\(/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PY-SQLI-001',
    name: 'Python SQL Injection via f-string or % Formatting in DB Cursor',
    severity: 'CRITICAL',
    cwe: 'CWE-89',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /cursor\.execute\s*\(\s*(?:f["']|["'].*?%s.*?["']\s*%|["'].*?\{\}.*?["']\s*\.format)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PY-YAML-001',
    name: 'Python Unsafe YAML Deserialization (yaml.load without SafeLoader)',
    severity: 'HIGH',
    cwe: 'CWE-502',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /yaml\.load\s*\([^)]*?(?:Loader\s*=\s*yaml\.(?:Loader|UnsafeLoader|FullLoader)|(?<!Loader\s*=)[^,)]*\))/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PY-PATH-001',
    name: 'Python Path Traversal via User Input in open() / os.path.join',
    severity: 'HIGH',
    cwe: 'CWE-22',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:open|os\.path\.join|os\.listdir)\s*\([^)]*?(?:request\.|args\.|form\.|sys\.argv)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PY-SHELL-001',
    name: 'Python Command Injection via os.system or subprocess(shell=True)',
    severity: 'CRITICAL',
    cwe: 'CWE-78',
    category: RULE_CATEGORIES.INJECTION,
    pattern: /(?:os\.system\s*\([^)]*?(?:request\.|args\.|form\.|sys\.argv|\+|\$)|subprocess\.(?:Popen|call|run|check_output)\s*\([^)]*?shell\s*=\s*True)/i,
    isLiteralSafe: false,
  },
  {
    id: 'SAST-PY-DEBUG-001',
    name: 'Python Flask/Django Production Debug Mode Enabled or Hardcoded SECRET_KEY',
    severity: 'HIGH',
    cwe: 'CWE-489',
    category: RULE_CATEGORIES.INFRA,
    pattern: /(?:DEBUG\s*=\s*True|SECRET_KEY\s*=\s*['"][a-zA-Z0-9_\-]{6,}['"])/i,
    isLiteralSafe: false,
  },
];

module.exports = {
  SAST_RULES,
  RULE_CATEGORIES,
};
